### ISSUE TITLE
Web Browser Interface must be updated

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-om20#12]
If test run is started via `Web Browser Interface`, it is still possible to select between `Conformance Classes` `Level 1` and `Level 2`.
However, the tests just support `Level 1`.
Thus, option to select `Level 2` must be removed from GUI. This also applies to the documentation on top of this page.

**Comment by epicureanism** [comment]
level 2 removed 2b8675df98f6abad01964ce09a11ebd3c4f56bef
