### ISSUE TITLE
Review and update conformance classes

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-om20#13]
There are 18 conformance classes mentioned in specification.
The test suite, however, just defines one class: `BasicConformanceClass`.
I cannot find any hint which of the 18 conformance classes are mandatory. So, I assume all of them are mandatory. What do you think @epicureanism ?

**Comment by epicureanism** [comment]
5 conformance classes were missing, and 13 conformance classes were mixed in the BasicConformanceClass.
To make it more clear, we've separated the conformance classes into different files.
We also added the missing ones.
16a40ba9458040e2dc412f4c7e95b4d2c601e29f
