### ISSUE TITLE
Update documentation to use "OMXML 2.0" instead of "OM 2.0"

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-om20#15]
The complete test suite should be checked for string "OM 2.0".

Background: https://github.com/opengeospatial/om-swg/issues/53#issuecomment-621049858

**Comment by keshavnangare** [comment]
@dstenger 

I have updated the documentation with OMXML 2.0 instead of OM 2.0. Please find the changes in PR #23.
