### ISSUE TITLE
Create unit tests for OMXML 2.0

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-om20#16]

**Comment by ghobona** [comment]
Update on 2020-07-15 @arieslai has  created the unit test and demonstrated to @ghobona today.

Agreement that @arieslai will test the unit tests on another machine and then create a pull request, and then @ghobona will review.

**Comment by ghobona** [comment]
@arieslai A reminder to create the Pull Request containing the unit test.

**Comment by arieslai** [comment]
Dear @ghobona ,

The unit test is added, also a XPath exception is found and fixed when running the test, it is due to the XPath syntax.
The pull request is made, thank you.
https://github.com/opengeospatial/ets-omxml20/pull/17
