### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-om20#18]
When running `mvn org.apache.maven.plugins:maven-dependency-plugin:analyze`, I get following warnings:
```
[WARNING] Used undeclared dependencies found:
[WARNING]    org.testng:testng:jar:6.8.8:compile
[WARNING]    net.sourceforge.saxon:saxon9:jar:9.0.0.8:compile
[WARNING]    net.sourceforge.saxon:saxon9-s9api:jar:9.0.0.8:compile
[WARNING]    xml-apis:xml-apis:jar:1.4.01:compile
[WARNING]    xerces:xercesImpl:jar:2.11.0:compile
[WARNING]    javax.ws.rs:jsr311-api:jar:1.1.1:compile
[WARNING] Unused declared dependencies found:
[WARNING]    commons-io:commons-io:jar:2.5:compile
[WARNING]    org.slf4j:slf4j-api:jar:1.6.1:compile
[WARNING]    com.google.inject:guice:jar:3.0:test
[WARNING]    org.slf4j:slf4j-simple:jar:1.6.1:compile
```
All used undeclared compile dependencies shall be declared in Maven pom file.
All unused declared dependencies shall be removed from Maven pom file.

**Comment by keshavnangare** [comment]
I have added used undeclared dependencies and removed unused declared dependencies except for the following dependency.

1. `com.google.inject:guice` is inherited from the parent and unable to exclude it.

Please find changes in #19 PR.

**Comment by dstenger** [comment]
@keshav-nangare Why did you add https://svn.opengeospatial.org/ogc-projects/cite/maven to the pom file? I think we should not use this repository anymore.

**Comment by dstenger** [comment]
@ghobona Do you know about the status of repository https://svn.opengeospatial.org/ogc-projects/cite/maven? It is also used by org.opengis.cite:schema-utils:1.5.

**Comment by dstenger** [comment]
@keshav-nangare Please update schema-utils dependency to 1.8.

**Comment by keshavnangare** [comment]
@dstenger 

I have updated the `ets-common` version to 9 which updates `schema-utils` version 1.8. Also, I have updated the other two required files for building the test suite. Please find the changes in the same PR.
