### ISSUE TITLE
Release notes are missing on project website

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-om20#2]
Project website is available [1] but the release notes are missing [2].

[1] http://opengeospatial.github.io/ets-om20/
[2] http://opengeospatial.github.io/ets-om20/changelog.html

**Comment by epicureanism** [comment]
fix release notes markdown file
https://github.com/opengeospatial/ets-om20/commit/a53b997229ad1c189afa71fcd55674854f833ca8
