### ISSUE TITLE
Improve name of test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-om20#3]
Currently, "Test suite ets-om20" is displayed as name of test suite on http://cite.opengeospatial.org/te2/ .

The name should be the name of the specification instead (see other test suites).

**Comment by epicureanism** [comment]
fix the name of test suite and correct version number
https://github.com/opengeospatial/ets-om20/commit/13d32d137091b9b49d7a5bec553ed941243fb532
