### ISSUE TITLE
Rename ctl artifact created during built

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-om20#4]
Currently, when project is built with Maven, an artefact with following file name is created:
* ets-om20-[VERSION]-ctl-scripts.zip

All other test suites use a different pattern. So, following file name should be used instead:
* ets-om20-[VERSION]-ctl.zip

**Comment by epicureanism** [comment]
fix ctl output filename
https://github.com/opengeospatial/ets-om20/commit/d9384f490ed978332706658a55dc9bb8b24b3764
