### ISSUE TITLE
Add conformance class configuration into the ets-om20 test

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-om20#6]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by epicureanism** [comment]
update settings of conformance classes
b623225e9dee61a26ea17a5eec38796eb88612be

**Comment by epicureanism** [comment]
settings of conformance classes are updated, we also created the dockerfile, the test suit works well in docker as well.
https://github.com/opengeospatial/ets-om20/commit/73c8c3c7c0d20de7716c4dda9fdc112eecac1abe

**Comment by lgoltz** [comment]
Enhanced README: https://github.com/opengeospatial/ets-om20/commit/c2534165a561fedbbc372457243a5ab2499c0f54

@epicureanism Do you know an available service for testing?

**Comment by epicureanism** [comment]
@lgoltz we only tested the sample xml existed on the resource folder, like https://raw.githubusercontent.com/opengeospatial/ets-om20/master/src/test/resources/CategoryObservation1.xml
