### ISSUE TITLE
Enhance entry page of the test suite (via TEAM Engine Web GUI) 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-om20#8]
The [main ctl](https://github.com/opengeospatial/ets-om20/blob/master/src/main/scripts/ctl/om20-suite.ctl) does not contain the test suite specific information.

**Comment by epicureanism** [comment]
The specific information for the ETS was updated https://github.com/opengeospatial/ets-om20/commit/a7bc6d0299db4b765a51b823cb1e6b80a56babe1
