### ISSUE TITLE
Test on test method of Spatial Parameter may cause java.lang.NullPointerException in Docker enviroment

### ISSUE THREAD

**Issue by epicureanism** [opengeospatial/ets-om20#9]
When test the test method of Spatial Parameter in the docker environment, the docker console returns the gml-3.2.1.xsd can not be found like the following message:
/org/opengis/cite/om20/xsd/opengis/gml/3.2.1/gml-3.2.1.xsd (No such file or directory)

And this error makes the teamengine display a test result of "java.lang.NullPointerException."

**Comment by dstenger** [comment]
@keshav-nangare Can you please analyse the reported bug?

**Comment by epicureanism** [comment]
Fixed. https://github.com/opengeospatial/ets-om20/commit/f12d14e637374e1c5660007cb58e9ab6e34b9d3c
It turns out that it's not the problem of docker, it's the problem of using the wrong method to retrieve the xsd file in the resource folder.
More details were discussed here: https://stackoverflow.com/questions/14089146/file-loading-by-getclass-getresource
